### ISSUE TITLE
Group tests in one describe block

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages-ubuntu#10]
If you groups specs like this:
```pp
describe 'One big test' do

  describe file('foo') do
    it { should be_file }
  end

  describe file('bar) do
    it { should be_file }
  end
[..]
end
```

spec_helper will load the vagrant instance only once and then perform all wanted checks

If not, for every single `describe` block, vagrant will be reloaded (from a snapshot state, but still expensive)

Will speed-up test execution!

**Comment by njam** [comment]
Aren't we always doing this already? E.g. memcached:
```ruby
require 'spec_helper'

describe 'memcached' do

  describe port(11211) do
    it { should be_listening }
  end

  describe command('monit summary') do
    its(:stdout) { should match /memcached/ }
  end

  describe file('/etc/memcached.conf') do
    it { should contain '-c 99' }
  end
end
```

**Comment by ppp0** [comment]
Need to cross-check! You might be right

**Comment by ppp0** [comment]
Correct, all tests seem to have this pattern. Closing
