### ISSUE TITLE
HID Multitouch support

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages-ubuntu#15]
```
sudo apt-get install xserver-xorg-input-multitouch
sudo nano /usr/share/X11/xorg.conf.d/50-multitouch.conf 
# then replace driver multitouch by driver hid-multitouch
# then reboot
```

We should verify is `X` reconfiguration needed (in my test I did reconfigure `X -configure`)?

**Comment by kris-lab** [comment]
Let's try to support both orientation: horizontal and vertical if possible with screen driver!

**Comment by ppp0** [comment]
Solved in https://github.com/cargomedia/puppet-packages/issues/980
