### ISSUE TITLE
Bluetooth audio devices support

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages-ubuntu#16]
1. Make sure USB-bluetooth is supported
2. Maybe install `bluez-alsa` support https://wiki.debian.org/Bluetooth/Alsa (TBD)
3. Prepare module for specific devices
 - register device by hardware adress XX:XX:XX:XX...
 - autoconnect
 - set device as standard sound output and input (should be in `audio-sink`/A2DP mode, not HFP/HSP)
4. Reconfigure pulseaudio server
 - `pulseaudio-module-bluetooth` can be missing

**Comment by ppp0** [comment]
Solved in https://github.com/cargomedia/puppet-packages/issues/978
