### ISSUE TITLE
Bluetooth usb dongle support for Broadcom

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages-ubuntu#17]
Most likely we will use [USB-Bluetooth dongle](http://plugable.com/2014/06/23/plugable-usb-bluetooth-adapter-solving-hfphsp-profile-issues-on-linux) which works with Ubuntu 15.04 but requires some driver/firmware upgrade to support HFP/HSP correctly.

[Steps](http://plugable.com/2014/06/23/plugable-usb-bluetooth-adapter-solving-hfphsp-profile-issues-on-linux)
```
wget https://s3.amazonaws.com/plugable/bin/fw-0a5c_21e8.hcd
sudo mkdir /lib/firmware/brcm
sudo mv fw-0a5c_21e8.hcd /lib/firmware/brcm/BCM20702A0-0a5c-21e8.hcd
sudo reboot
```

More info:
- https://bugs.launchpad.net/ubuntu/+source/bluez/+bug/962082
- http://askubuntu.com/questions/180437/bluetooth-headset-a2dp-works-hsp-hfp-not-no-sound-no-mic

**Comment by ppp0** [comment]
Solved in https://github.com/cargomedia/puppet-packages/issues/979
