### ISSUE TITLE
Decklink/Blackmagic driver

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages-ubuntu#2]
##### BIOS
Make sure the PCI Express configuration of motherboard fits requirements of Blackmagic card. Currently the Decklink/Blackmagic uses `PCI Express of 2nd` generation so the motherboard setting has to be updated (4th generation is default e.g. for Asus)

##### Listing PCI
```sh
lspci | grep Blackmagic
# 03:00.0 Multimedia video controller: Blackmagic Design DeckLink Studio 4K
```

##### Install drivers
```sh
# should work
sudo apt-get install desktopvideo
# if not, check for the newest drivers
wget "http://sw.blackmagicdesign.com/DesktopVideo/v10.5/Blackmagic_Desktop_Video_Linux_10.5.tar.gz
tar xfv Blackmagic_Desktop_Video_Linux_10.5.tar.gz
cd Blackmagic_Desktop_Video_Linux_10.5
sudo dpkg -i desktopvideo_*.deb
```

##### Load kernel modules
```
modprobe blackmagic
modprobe blackmagic_io
```

##### Verify kernel modules
```
lsmod | grep blackmagic
# blackmagic            585728  0
# blackmagic_io         430080  1 
```

##### List Blackmagic devices
```
ls /dev/blackmagic/*
# io0  ttyio0
```

##### Verify PCI and Upgrade
```
/usr/bin/BlackmagicFirmwareUpdater status
# 0:	/dev/blackmagic/io0 [DeckLink Studio 4K]	0x7d	OK

/usr/bin/BlackmagicFirmwareUpdater update /dev/blackmagic/io0
# /dev/blackmagic/io0 firmware update completed successfully.                                    
# Please reboot your system now to activate new firmware
```

##### Update Gstreamer
It must be in version `1.5.2` or higher. Please follow [this step](https://github.com/cargomedia/rndmvr/issues/16#issuecomment-120643250) to install `gst-plugins-bad` which includes `Decklink` support.

##### Running Gstreamer
```sh
$ gst-launch-1.0 -v decklinkvideosrc connection=hdmi ! queue ! videoconvert ! vp8enc ! webmmux ! filesink location=/tmp/test.webm
```

**Comment by ppp0** [comment]
Solved in https://github.com/cargomedia/puppet-packages/issues/975
